lyndsey-ferguson/fastlane-plugin-test_center

lib/fastlane/plugin/test_center/actions/collate_html_reports.rb
lib/fastlane/plugin/test_center/actions/collate_json_reports.rb
lib/fastlane/plugin/test_center/actions/collate_junit_reports.rb
lib/fastlane/plugin/test_center/actions/collate_test_result_bundles.rb
lib/fastlane/plugin/test_center/actions/multi_scan.rb
lib/fastlane/plugin/test_center/actions/suppress_tests.rb
lib/fastlane/plugin/test_center/actions/suppress_tests_from_junit.rb
lib/fastlane/plugin/test_center/actions/suppressed_tests.rb
lib/fastlane/plugin/test_center/actions/tests_from_junit.rb
lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb

The actions all should work with Xcode related artifacts. They all declared that they only work for the iOS platform, but not the Mac platform. This change fixes that [Issue 64](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/64).
Added `:mac` as another supported platform.

issue-64 add mac support annotation

---

fastlane-plugin-test_center.gemspec

Fixes #74 
As of Xcode 10, the `xctest_list` gem was unable to find Swift tests. That gem has been updated and _requiring_ that fixed version or later allows `multi_scan` to find the tests.
See above

issue-74 find xcode swift 4 tests

---

lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb
spec/fixtures/fake.xctestrun

Resolves an issue where a new entry in the `xctestrun` file is not an actual testable, but metadata. When `tests_from_xctestrun` encounters this entry, it breaks.
Skip the block if the key is `__xctestrun_metadata__`. Update the `xctestrun` fixture to include this new entry.

fix issue-77 new __xctestrun_metadata__ entry in testables

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/REGRESSION.md
fastlane/Fastfile
lib/fastlane/plugin/test_center/actions/collate_junit_reports.rb
lib/fastlane/plugin/test_center/actions/multi_scan.rb
spec/collate_junit_reports_spec.rb
spec/collate_test_result_bundles_spec.rb

This fixes issue-79: when Xcode has been configured to continue running a test after a failure, it generates a new test entry in the junit file. The collation of units was unable to handle duplicate entries for the same test case.
Moves all failure entries for testcase entries that are the same, but with different failures, into one testcase and remove the redundant ones. If the testcase passes later, the collation will remove the entire single element. 

Issue-79 multi_scan fails for xcodebuild server death

---

fastlane/Fastfile
lib/fastlane/plugin/test_center/actions/collate_junit_reports.rb
spec/collate_junit_reports_spec.rb

This change adds analytical data to the Junit report to indicate how many times a test was "retried" and how many times the entire test-run was "retried". 
Update the `collate_junit_reports` action to update a "retries" attribute to the number of other test reports that were run and update each test "retries" attribute to the number of times that the test was sent back to `xcodebuild test`.

Issue-43 retrycount passrate in junit

---

lib/fastlane/plugin/test_center/actions/multi_scan.rb
lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb
spec/correcting_scan_helper_spec.rb

Hello 👋 there,
Thanks for all the hard work in this library, it has been saving me from a lot of pain in my tests suites 😅.
The main motivation for this PR is regarding running UI tests with a predefined location. We can use this very good [repository](https://github.com/lyft/set-simulator-location) from Lyft to set a location in the simulator before running the tests but the simulator needs to be kept open before running the tests, otherwise, the simulator would fail in setting the location and tests would fail.
The behavior of `scan` by default is to keep the simulator in his current state (I tested several times)
Add the new `quit_simulators` parameter to avoid the simulator being shutting down before running the tests. Resolve #88.
I set the name `quit_simulators` but I don't have any …

Add the new quit_simulators parameter

---

lib/fastlane/plugin/test_center/actions/collate_html_reports.rb
lib/fastlane/plugin/test_center/actions/collate_json_reports.rb
lib/fastlane/plugin/test_center/actions/collate_junit_reports.rb
lib/fastlane/plugin/test_center/actions/collate_test_result_bundles.rb
lib/fastlane/plugin/test_center/actions/multi_scan.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/parallel_test_batch_worker.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/simulator_helper.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/test_batch_worker_pool.rb
spec/multi_scan_manager/parallel_test_batch_worker_spec.rb
spec/multi_scan_manager/retrying_scan_helper_spec.rb
spec/multi_scan_manager/runner_spec.rb
spec/multi_scan_manager/simulator_helper_spec.rb
spec/multi_scan_manager/test_batch_worker_pool_spec.rb

Fixes issue [Parallelization Bug: reports for batches with spaces in the testable name are not collated properly](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/109)
Fix a couple of issues:
1. spaces in names of testables would break the final collation
2. the first batch report was not generated in a testable-subdirectory
3. the final report for a single testable was not placed in the expected
place, breaking CI expecting the final report to be there and be fully
collated.

Fix collating of batched reports

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/test_batch_worker_pool.rb

Sometimes, while using the `parallel_testrun_count` option, all parallel test runs will fail with an error that the simulator failed to boot and that the testmanagerd failed to connect.
I had forgotten to include the pre-boot of the cloned Simulators in my refactoring of the parallelization of mulit_scan. This change includes the pre-boot of all cloned simulators. It does slow down the process initially, but provides a much higher degree of success.

issue-111 pre-boot cloned simulators

---

AtomicBoy/KiwiTests/KiwiTests.m
lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb
lib/fastlane/plugin/test_center/helper/test_collector.rb
spec/multi_scan_manager/retrying_scan_helper_spec.rb
spec/multi_scan_manager/runner_spec.rb

Fixes [Issue 113 ](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/113) by properly setting up parameters for the initial run of invocation based tests and parallelizes subsequent runs of failed test suites.

issue-113 fix parallelized invocation based tests

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/parallel_test_batch_worker.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/test_batch_worker.rb
spec/multi_scan_manager/parallel_test_batch_worker_spec.rb

Fixes an issue where parallel test runs would return _only_ return false. It was impossible for it to return the true result.
1. Add tests that confirm that the code was broken, and then confirmed that the new code fixes the test.
2. Fix test worker to actually get the test run status rather than the worker's `:state`.
3. Fix the parallel test work to properly test the pipe's result. Before, it had a new line as that is what `puts` does. I remove any newlines before comparing the result to `true`.

issue-117 fix parallel test runs returning false

---

lib/fastlane/plugin/test_center/helper/test_collector.rb
spec/test_collector_spec.rb

fastlane's `scan` supports receiving a String for the `:only_testing` option. `multi_scan` crashes with such a parameter.
Convert the the `:only_testing` parameter to an `Array` if it is a `String`. Add a test.

Issue 75 only testing expecting array

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb
spec/multi_scan_manager/runner_spec.rb

Users want the `:skip_build` option supported to let `xcodebuild` decide when to build or not. Previously, I did not support this as I wanted to use the `xctestrun` file to inform which tests should run. 
Change the single run of scan to run for both invocation tests and skip_build tests.

issue-41 support skip_build

---

README.md
lib/fastlane/plugin/test_center/actions/collate_junit_reports.rb
lib/fastlane/plugin/test_center/actions/multi_scan.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb
spec/collate_junit_reports_spec.rb
spec/multi_scan_spec.rb

Fixes an issue where the `multi_scan` summary contains `nil` for the total retry count.
1. Update how we collate junit reports to update the retry count by taking into account the number of reports were used to collate into the main one.
2. Gather the retry count from the junit report rather than depending on the runner's retry counts.

Issue-124 total retry count is nil

---

lib/fastlane/plugin/test_center/helper/test_collector.rb
spec/test_collector_spec.rb

This resolves #132, which is a regression in 3.8.0 where using the `only_testing` option with multiple test targets results in the tests only being collected from one of the targets.
I've tested this change locally on a project with several test targets and have verified that it works now as expected.
I'd like to add test coverage for this PR, since this regression wasn't caught by the existing tests, but I had a hard time figuring out the best way to simulate this scenario, and would love feedback or assistance so I can make sure this change is covered properly.
This change simply changes the initializer of `known_tests` to an empty array, and changes the `||=` operator to `+=` to correctly collect the tests.

issue-132 populate known_tests with all tests

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb
spec/multi_scan_manager/retrying_scan_helper_spec.rb

Fixes a number of issues brought up in #142: 
- calling `:testrun_completed_block` when `xcodebuild` fails and no junit report file is created can inadvertently cause a crash.
- clients can pass `build-for-testing` in xcargs, which, when combined with running scan with 'test-without-building', will cause `xcodebuild` to crash.
1. Provide either failing tests or an empty array to the `testrun_completed_block` callback for both failing and passing tests.
2. Explicitly remove `build-for-testing` from `xcargs`

issue-142 remove build-for-testing from xcargs

---

lib/fastlane/plugin/test_center/actions/collate_html_reports.rb
lib/fastlane/plugin/test_center/helper/html_test_report.rb
spec/collate_html_reports_spec.rb
spec/fixtures/atomicboy_uitestsuite-2.html
spec/fixtures/atomicboy_uitestsuite-3.html
spec/fixtures/atomicboy_uitestsuite-4.html
spec/fixtures/atomicboy_uitestsuite.html
spec/fixtures/report-2.html
spec/fixtures/report-4.html
spec/fixtures/report-5.html
spec/html_test_report_spec.rb

Resolves #126.
There are two known problems with the collation of HTML reports:
1. collated tests are placed outside of the `<table/>` and this breaks the formatting of the HTML page.
2. collated tests do not properly alternate background colors per row.
- Add smaller, more exact functions for getting information from testsuites, testcases
- Add smaller functions for merging testcases into testsuites

Issue-126 fix html collation

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/report_collator.rb

Addresses crashing issue #136 where collation of single files would fail if, via some mechanism, the file being moved is the same, but a string comparison of absolute paths yields that they are not the same file.
I tested via `rake` and running `multi_scan` on the sample project with `result bundles` and `html` and `junit` report files. With no batches and a try count of 1.
Use `File.identical?` for file comparison when moving the 1 report file to the final file. Use `File.realdirpath` to get the real path of test result directories.

issue-136 better test for identical file for report collating

---

AtomicBoy/AtomicBoy.xcodeproj/project.pbxproj
lib/fastlane/plugin/test_center/actions/multi_scan.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/simulator_helper.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/test_batch_worker_pool.rb
spec/multi_scan_manager/simulator_helper_spec.rb
spec/multi_scan_spec.rb

This fixes two issues: #148, a crash when the client passes in a string for the `:destination` which works fine on `scan`, and #146  with running parallel `multi_scans` in parallel: deletion of the cloned simulators.
1. For the first issue, I coerce the `:destination` parameter to an array.
2. For the second issue, I provide a new option to _not_ delete the cloned simulators before running `multi_scan` in parallel.

Fixes issue 148 and issue 146

---

.github/workflows/main.yml
lib/fastlane/plugin/test_center/helper/html_test_report.rb
spec/html_test_report_spec.rb

This fixes a crashing Issue #150 that occurs on Ruby 2.6.x when collating HTML files.
1. Remove some complexity from how individual test cases are found by name to avoid some issues in REXML for Ruby 2.6.x.
2. Loosen up the coupling for what nodes are searched for.
3. Add a Ruby 2.6.x matrix for testing that version.

Issue 150 crash with html collation ruby 2.6.x

---

lib/fastlane/plugin/test_center/actions/collate_test_result_bundles.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/report_collator.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb

Updates how test_results are collated for Xcode 11. The Info.plist file no longer contains the tests in the Info.plist file.

Issue 145 crash when collating test bundles

---

lib/fastlane/plugin/test_center/actions/collate_test_result_bundles.rb

`collate_test_result_bundles` was broken before releasing `3.8.7` due to insufficient testing after refactoring. This fixes that issue #145.

issue-145 fix broken collate_test_result_bundles refactor

---

lib/fastlane/plugin/test_center/actions/collate_test_result_bundles.rb

Many times scheme names could have space. This results in failure, this PR will resolve that
https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/159
Ran all the tests suggested by repo
Just added shellescape to https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/16599a56dad0f3e5f7b490c5123be20e9a27889e/lib/fastlane/plugin/test_center/actions/collate_test_result_bundles.rb#L62

Added shellscape for result bundle files

---

lib/fastlane/plugin/test_center/actions/multi_scan.rb

Fixes Issue #165. When calling `multi_scan` with the `:test_without_building` option, it will conflict with the request to `:build_without_testing` option.
Remove the `:test_without_building` option when requesting `scan` to build.

issue-165 fix test_without_building build conflict

---

.github/workflows/main.yml

Ruby 2.3.x is no longer available in the Github Actions. Tests are showing up as failed.
Removed 2.3.x and added 2.5.x.

Fix 'Run Tests' Workflow

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/report_collator.rb

Fixes issue #169 where the test_result bundles were renamed inappropriately and caused subsequent retries to fail when the unexpected test_result bundle already existed.
Fix the suffix for the collated test_result bundle file.

fix issue-169 multi_scan crash when collating test_results

---

.rubocop.yml
fastlane-plugin-test_center.gemspec
fastlane/Fastfile
lib/fastlane/plugin/test_center/actions/multi_scan.rb

As per #182, `multi_scan` will crash if it is given a comma separated list of `:output_types` with spaces after the commas.
Remove the spaces as soon as `multi_scan` starts.

issue-182 remove spaces between report types

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb
spec/multi_scan_manager/retrying_scan_helper_spec.rb

Fix issue #180 where tests that crash are not retried.
When a test fails, it is reported and is retried. If a test crashes, it is not recorded as failing and thus is not retried.
Instead of retrying failing tests, retry the tests that are left over from the original list of tests.

issue-180 better handle crashing tests for retry

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb
spec/multi_scan_manager/retrying_scan_helper_spec.rb

Developers sometimes include the command `-parallel-testing-enabled` in the `multi_scan` command when it will not work: it defeats the mechanism the tool has for finding failed tests in previous runs. This is described in #189 .
`multi_scan` intentionally disables parallel testing done this way, but when passed in `xcargs` it can be read first and turn on parallel testing even though a subsequent `xcarg` will turn it off.
Remove any `-parallel-testing-enabled` `xcarg` before `multi_scan` sets it to `NO`.

issue-189 remove pre-existing -parallel-testing-enabled xcargs

---

lib/fastlane/plugin/test_center/actions/multi_scan.rb
spec/multi_scan_spec.rb

Address issue #183 by warning of potential problems when parallelizing with `multi_scan` on Circle CI issues.
1. Check for parallelism and Circle CI.
1. Refactored `run` method for `multi_scan` to be a little cleaner and easy to read.

issue-183 warn when parallelizing on Circle CI

---

fastlane/Fastfile
lib/fastlane/plugin/test_center/helper/multi_scan_manager/simulator_helper.rb

Issue #178, `multi_scan` will fail when parallelizing tests because it cannot duplicate the found simulator if it is specified via the `destination` field.
Updated the code that clones the chosen simulators by using the id OR the details of the name and the OS version.

issue-178 clone sims by name, not id

---

lib/fastlane/plugin/test_center/actions/multi_scan.rb
spec/multi_scan_spec.rb

Fixes #193 , a new feature from fastlane that turns on concurrent workers, which `multi_scan` does not support for retrying tests.
Check if version of fastlane that supports this new option, and if it was given, removes that option from those that are passed down to `scan`.

issue-193 disable concurrent workers

---

fastlane/Fastfile
lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb

This fixes #207 which occurs when the `:result_bundle` environment variable is set and a double `resultBundlePath` is sent to `xcodebuild` (which crashes it).
Clear out the following environment variables as well as the other `scan_options`:
- `SCAN_DEVICE`
- `SCAN_DEVICES`
- `SCAN_RESULT_BUNDLE`

issue-207 clear out result bundle env var

---

lib/fastlane/plugin/test_center/helper/test_collector.rb
spec/test_collector_spec.rb

When [v3.10.0](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/tree/v3.10.0) was released, it introduced #212 which broke testing.
Get the testables based on the test targets that the action `tests_from_xctestrun` action: it handles v1 and v2 of the `xctestrun` files.

issue-212 fix v2 xctestrun files test collection

---

fastlane/Fastfile
lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb
lib/fastlane/plugin/test_center/helper/test_collector.rb
spec/multi_scan_manager/retrying_scan_spec.rb

Investigate #119 and found out that it now works. I probably fixed it in an earlier change. I cleaned this code up to no longer print it out as one of the tests that are skipped as that _could_ conflict with the only testing parameter sent to `scan`.
Remove `:skip_testing` from the options sent to `scan` for each test run.

issue-119 clean up skip_testing option

---

fastlane/Fastfile
lib/fastlane/plugin/test_center/actions/multi_scan.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb

As reported in #225, using the `-quiet` flag in the `:xcargs` parameter will prevent tests from being reported: this causes `:multi_scan` to _not_ retry tests.
Setting `:try_count` to a value less than 0 will cause `multi_scan` to not try _any_ tests. 
Remove the '-quiet' flag with a warning and pin `:try_count` to a mininum of 1.

issue-225 disable '-quiet' and 'try_count' < 0

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb
spec/multi_scan_manager/retrying_scan_helper_spec.rb

After changing multi_scan to handle re-running only "non-failed" tests,
a bug was introduced where the 'invocation' tests aspect of the plugin
would fail after a test run. This fixes that.
Fixes issue #219 to prevent crashes after a test run with the invocation tests option is selected.
Get an empty array if `:only_testing` is empty or nil.

issue-219 Handle invocation tests for first run properly

---

.rubocop.yml
docs/feature_details/test_options_from_testplan.md
docs/feature_details/testplans_from_scheme.md
fastlane/Fastfile
lib/fastlane/plugin/test_center/actions/multi_scan.rb
lib/fastlane/plugin/test_center/actions/test_options_from_testplan.rb
lib/fastlane/plugin/test_center/actions/testplans_from_scheme.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb
lib/fastlane/plugin/test_center/helper/test_collector.rb
spec/fixtures/code-coverage-no.xctestplan
spec/fixtures/code-coverage.xctestplan
spec/test_options_from_testplan_spec.rb
spec/testplans_from_scheme_spec.rb

As reported in #221 , if the `:testplan` option is presented to `multi_scan`, and it needs to build, it will pass that option to `xcodebuild build-for-testing` and that will cause `xcodebuild` to fail with an error that those options are conflicting.
Remove `:testplan` option from the build command.

issue-221 prevent testplan crash when building

---

AtomicBoy/AtomicBoy.xcworkspace/contents.xcworkspacedata
AtomicBoy/SuperAtomicBoy_2.xctestplan
fastlane/Fastfile
lib/fastlane/plugin/test_center/actions/multi_scan.rb

This fixes #232 where the wrong test plan is used to run tests. 
This refine the shell glob used to find the `xctestrun` bundle associated with the given `:testplan`.

issue-232 refine xctestrun glob for testplans

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb

Fixes #230 which crashes when there is no xcresult file to merge from or into.
Exit from the merge if there is either no destination xcresult bundle to merge into, or there is no source xcresult bundle to merge from.

issue-230 fix not found xcresult crash

---

lib/fastlane/plugin/test_center/actions/test_options_from_testplan.rb

Issue #237 demonstrates that Swift tests from a testplan are not correctly retrieved. This causes a failure in `multi_scan` when it tries to determine which tests to retry and it ends up retrying all tests.
Remove the `()` from Swift tests when collecting them from a testplan.

issue-237 fix test retrieval from testplans

---

lib/fastlane/plugin/test_center/actions/testplans_from_scheme.rb
spec/testplans_from_scheme_spec.rb

When Xcode Schemes are stored inside the Workspace, an error occurs when trying to construct the file path to the testplans as per #231.
1. Change the path to the "container" to allow it to be inside a `xcworkspace` or an `xcodeproj`.
1. Update code to get Schemes to first look inside the workspace when that option is given.
1. Update code to only look at projects referenced by a workspace when workspace is the given option.
1. Refactor `testplans_from_scheme.rb` into smaller methods.

Fix issue with workspace schemes and testplans

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/simulator_helper.rb

As per #216, when devs state that they want multiple simulators tested, multi-scan only scans on one of the devices when running tests in parallel.
1. Stop looping through the list of requested sims when filtering through all the devices.
1. When one is found, we can remove the found device from the list and look for the next one.
1. Refactor the match checking code into its own method.

issue-216 clone all desired sims for parallel runs

---

spec/multi_scan_manager/simulator_helper_spec.rb

Adds a test to make sure that when parallel test runs are chosen, and multiple destinations for simulator tests, `multi_scan` clones all the destinations for each test run.
Add the test to make sure that all destinations are cloned.

Add test for issue-232 multi-destination sims

---

lib/fastlane/plugin/test_center/actions/multi_scan.rb

Fixes Issue #243 where testplans are not being found again.
Use the `%i[]` symbol array creation correctly.

issue-243 fix testplans w sim log collection

---

lib/fastlane/plugin/test_center/helper/html_test_report.rb
spec/fixtures/report-6.html
spec/html_test_report_spec.rb

Issue #250 describes a crash when collating HTML reports and, for some reason, the failure details of a failing test is missing.
1. Only delete the failure details element if it exists
2. Favor deleting failing duplicated testcases over passing duplicated testcases
3. Add rspec tests for handling missing failure details and ensuring that failing duplicated testcases are deleted first.

issue-250 fix collate crash w/ no failure details

---

lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb
spec/fixtures/fake.xctestrun
spec/tests_from_xctestrun_spec.rb
spec/xctestrun_info_spec.rb

Fixes #261 by getting the testable name in a different way.

issue-261 get correct testable name from xctestrun file

---

lib/fastlane/plugin/test_center/actions/multi_scan.rb
lib/fastlane/plugin/test_center/helper/fastlane_core/device_manager/simulator_extensions.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/device_manager.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb

This address Issue #248 where the simulators are being retrieved from a simulator that has not run the tests. There is a [fastlane PR 16833](https://github.com/fastlane/fastlane/pull/16833) open, but this fix should be available for older versions of fastlane.
If the `FastlaneCore::Simulator` class does not have the `:prelaunch_simulators` method, we patch it with a fixed copy of the method.

issue-250 fix older fastlane sim log collection

---

fastlane/Fastfile
lib/fastlane/plugin/test_center/actions/multi_scan.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb
lib/fastlane/plugin/test_center/helper/scan_helper.rb
spec/multi_scan_manager/runner_spec.rb

multi_scan does things differently in a way that makes the :skip_build
option extraneous. Stop using it and just set it to false.
As per #252, `multi_scan` is not responding to the `:skip_build` option in a way that make sense.
- Remove the special handling of `:skip_build`.
- Remove `:skip_build` as it doesn't make sense in the way that `multi_scan` works.

issue-252 remove :skip_build from scan options

---

docs/feature_details/multi_scan.md
fastlane/Fastfile
lib/fastlane/plugin/test_center/actions/multi_scan.rb

This will fix issue #253 in which the `xcresult` `:output_type` is passed down to `scan` and generates a warning. Also clears up some confusion around the feature in the documenation.
This strips out the xcresult type (and associated filename) from the
options that are being sent to scan when building.
Also improve the documentation around the `xcresult` output_type option
to explain a little more what it is doing and why multi_scan is _not_
sending down the `result_bundle`, and why a symbolic link is being
created if the `result_bundle` option was chosen.

issue-253 No xcresult output_type for scan and better documentation

---

fastlane/Fastfile
lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb
lib/fastlane/plugin/test_center/helper/test_collector.rb
spec/multi_scan_manager/runner_spec.rb

As per issue #254, it was discovered that there were a number of anomalies around how `:multi_scan` handles batches and parallel test runs.
This improves the logic around the creation of simulator clones to
account for a reduced number of tests. If there are fewer tests than the
requested parallel_test_runs, reduce the number of simulators to the
number of tests.
Additionally, if there was only 1 batch requested, stop prefixing
results with the batch number and output directly to the requested
output folder.

issue-254 improve batch and parallel testrun logic

---

.github/workflows/merge.yml
.rubocop.yml
fastlane/Fastfile
lib/fastlane/plugin/test_center/helper/test_collector.rb
spec/test_collector_spec.rb

This fixes issue #268 where the method to expand testsuites into full
test identifiers would include tests that belonged to testsuites with a
name that included other testsuites.
For example: if expanding Foo, it would get tests for Foo, and for
FooBar.
- look for the exact suite name in the given testable
- add tests for this specific case

issue-268 fix massive test duplication

---

lib/fastlane/plugin/test_center/helper/test_collector.rb
spec/test_collector_spec.rb

Fixes #271 where providing test targets via `:only_testing` does not expand them out to all the tests in the test target.
Add all the tests for a given test target if it is found that the provided identifier matches the test target.

Issue 271 only testing test targets not expanded

---

lib/fastlane/plugin/test_center/actions/multi_scan.rb
spec/multi_scan_spec.rb

`scan` provides an option to disable the use of xcpretty. xcpretty is used to generate the junit report files in `multi_scan` and those reports contain the information needed to determine whether or not to retry tests. Without that option, `multi_scan` will crash, as described in #275 .
Strip out the `:disable_xcpretty` option from the list of options.

issue-275 omit disable xcpretty option

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/test_batch_worker_pool.rb

Addresses issue #291 where `multi_scan` attempts to manipulate `Scan.devices` (simulators) for macOS tests. That is invalid, and crashes.
Check the platform before working with `Scan.devices`

issue-291 Use Scan.devices only for ios tests

---

lib/fastlane/plugin/test_center/helper/test_collector.rb

This fixes issue #293 where tests were not found and `multi_scan` exited early.
This fixes a typos where the variable name that was used to collect tests was not the variable name used to add the tests to the list of only_testing.

issue-293 fix expansion of test identifiers

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb

This fixes another issue introduced by a merge where `multi_scan` will crash when running macOS tests. See the end of #291 for info regarding the crash. 

issue-291 Fixes macOS tests crash from merge

---

lib/fastlane/plugin/test_center/helper/fastlane_core/device_manager/simulator_extensions.rb

This improves the log_archive patch method for the
FastlaneCore::Simulator class to include a start time from when to start
collecting logs (start of multi_scan session).
Users of fastlane with a version that does not have the fix to collect logs from a start time will not have that ability in this plugin. This updates that.

Enhance sims log collection to include start time

---

lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb

This fixes #303 when `Scan.devices` is nil. I really should look into how this becomes nil though. I will after I see if this fixes the issue.
Set `Scan.devices` if it is nil, otherwise `replace` the contents.

issue-303 multi_scan crash if Scan.devices nil

---

docs/feature_details/collate_html_reports.md
docs/feature_details/collate_junit_reports.md
lib/fastlane/plugin/test_center/actions/collate_junit_reports.rb
lib/fastlane/plugin/test_center/helper/html_test_report.rb

Address #299 .
This allows users to turn off verbose messaging by setting the
environment variables COLLATE_HTML_REPORTS_VERBOSITY=0 and/or
COLLATE_JUNIT_REPORTS_VERBOSITY=0
Refactored the calls to the `UI.verbose` method to be class methods that check if the environment variable is set to 1 (default 1) before logging.

issue-299 Support turning off verbose msgs

---

lib/fastlane/plugin/test_center/actions/tests_from_xcresult.rb

This adds new functionality requested by a user in #327 to gather "skipped" tests from an xcresult file.
Add skipped tests to the information reported by the `tests_from_xcresult` action.

issue-327 support skipped test identifiers in xcresult

---

.github/workflows/main.yml
.rubocop.yml
fastlane-plugin-test_center.gemspec

Fixes https://github.com/fastlane/fastlane/issues/19834
Fixes https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/374
Addresses the stale PR: https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/pull/375 with suggestions from comments
_fastlane_ 2.201.0 now has `trainer` built into it. `trainer` was a dependency of `test_center` but no longer needs to be. `trainer` has been removed and `fastlane` is now required to be `>= 2.201.0`.

Remove trainer dep update fastlane

---

fastlane-plugin-test_center.gemspec

Fixes https://github.com/fastlane/fastlane/issues/19834
Fixes https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/374
_fastlane_ 2.201.0 now has `trainer` built into it. `trainer` was a dependency of `test_center` but no longer needs to be. `trainer` has been removed and `fastlane` is now required to be `>= 2.201.0`.

[gemspec] Remove trainer dependency and update fastlane

---

lib/fastlane/plugin/test_center/actions/collate_xcresults.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/report_collator.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb
lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb
spec/collate_xcresults_spec.rb

Fixes #328 by normalizing the path names for potential source and destination to lowercase to ensure that we're discounting case differences in macOS.
Use the `:downcase` method on both the source and destination path before comparing in the collate xcresult method.

issue-327 downcase xcresult paths for comparison
